### ISSUE TITLE
[Tech Debt] Cleanup build warnings

### ISSUE THREAD

**Issue by tpill90** [tpill90/battlenet-lancache-prefill#37]
This project's build is currently throwing various warnings

## Task List

- [ ] Resolve all build/analyzer warnings
- [ ] Resolve SingleFile/Trim publish warnings
- [ ] Configure Github Actions to fail the build when there are any warnings
